export const API_PREFIX = "/api/v1";

export const ApiPaths = {
  health: `${API_PREFIX}/health`,
  /** Public marketing/checkout flags (no auth). */
  featureFlags: `${API_PREFIX}/feature-flags`,
  authSignup: `${API_PREFIX}/auth/signup`,
  authLogin: `${API_PREFIX}/auth/login`,
  authLogout: `${API_PREFIX}/auth/logout`,
  me: `${API_PREFIX}/me`,
  meProfile: `${API_PREFIX}/me/profile`,
  venues: `${API_PREFIX}/venues`,
  venue: (id: string) => `${API_PREFIX}/venues/${id}`,
  venueAvailability: (id: string) => `${API_PREFIX}/venues/${id}/availability`,
  venueCourts: (id: string) => `${API_PREFIX}/venues/${id}/courts`,
  venueReviews: (id: string) => `${API_PREFIX}/venues/${id}/reviews`,
  bookings: `${API_PREFIX}/bookings`,
  booking: (id: string) => `${API_PREFIX}/bookings/${id}`,
  bookingCheckout: (id: string) => `${API_PREFIX}/bookings/${id}/checkout`,
  bookingCancel: (id: string) => `${API_PREFIX}/bookings/${id}/cancel`,
  bookingCancelPolicy: `${API_PREFIX}/bookings/cancel-policy`,
  notifications: `${API_PREFIX}/notifications`,
  notificationsRead: `${API_PREFIX}/notifications/read`,
  games: `${API_PREFIX}/games`,
  game: (id: string) => `${API_PREFIX}/games/${id}`,
  gameJoin: (id: string) => `${API_PREFIX}/games/${id}/join`,
  gameLeave: (id: string) => `${API_PREFIX}/games/${id}/leave`,
  matches: `${API_PREFIX}/matches`,
  matchResult: (id: string) => `${API_PREFIX}/matches/${id}/result`,
  matchConfirm: (id: string) => `${API_PREFIX}/matches/${id}/confirm`,
  paymentsWebhook: `${API_PREFIX}/payments/webhook`,
  paymentsConfig: `${API_PREFIX}/payments/config`,
  adminUsers: `${API_PREFIX}/admin/users`,
  adminUsersRoles: `${API_PREFIX}/admin/users/roles`,
  adminVenues: `${API_PREFIX}/admin/venues`,
  adminVenueStatus: `${API_PREFIX}/admin/venues/status`,
  adminCourts: `${API_PREFIX}/admin/courts`,
  adminCourtActive: `${API_PREFIX}/admin/courts/active`,
  adminBookings: `${API_PREFIX}/admin/bookings`,
  adminBookingStatus: `${API_PREFIX}/admin/bookings/status`,
  adminPayments: `${API_PREFIX}/admin/payments`,
  adminPaymentStatus: `${API_PREFIX}/admin/payments/status`,
  adminGames: `${API_PREFIX}/admin/games`,
  adminGameStatus: `${API_PREFIX}/admin/games/status`,
  adminMatches: `${API_PREFIX}/admin/matches`,
  adminNotifications: `${API_PREFIX}/admin/notifications`,
  adminFeatureFlags: `${API_PREFIX}/admin/feature-flags`,
  adminDashboard: `${API_PREFIX}/admin/dashboard`,
  adminReports: `${API_PREFIX}/admin/reports`,
  adminAudit: `${API_PREFIX}/admin/audit`,
  adminExport: `${API_PREFIX}/admin/export`,
  venueDashboard: `${API_PREFIX}/venue/dashboard`,
  venueCalendar: `${API_PREFIX}/venue/calendar`,
  venueStaff: `${API_PREFIX}/venue/staff`,
  venueAvailabilityRules: `${API_PREFIX}/venue/availability-rules`,
  venuePricingRules: `${API_PREFIX}/venue/pricing-rules`,
  venueBlackouts: `${API_PREFIX}/venue/blackouts`,
} as const;
